name: todo_app
description: ToDo app

publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  get:
  path_provider:
  responsive_framework:
  local_auth:
  flutter_svg:
  sqflite:
  share_plus:
  google_fonts:

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  flutter_launcher_icons: "^0.12.0"



  flutter_lints: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21

flutter:


  uses-material-design: true

    #Project assets
  assets:
    - assets/lang/
    - assets/icons/
    - assets/images/
